Add testing to pre-commit hook

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -56,4 +56,10 @@ if [[ $? -ne 0 ]]; then
   exit_gracefully 1
 fi
 
+stack test
+if [[ $? -ne 0 ]]; then
+  echo -e "\e[31mThere were test failures - fix the above issues and try again.\e[0m"
+  exit_gracefully 1
+fi
+
 exit_gracefully 0
