Add CI build job and turn on -Werror in the pre-commit hook

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -56,7 +56,14 @@ if [[ $? -ne 0 ]]; then
   exit_gracefully 1
 fi
 
-stack test
+stack clean
+stack build --fast --ghc-options -Werror
+if [[ $? -ne 0 ]]; then
+  echo -e "\e[31mBuild failed - fix the above issues and try again.\e[0m"
+  exit_gracefully 1
+fi
+
+stack test --fast --ghc-options -Werror
 if [[ $? -ne 0 ]]; then
   echo -e "\e[31mThere were test failures - fix the above issues and try again.\e[0m"
   exit_gracefully 1
