Add vault (#1)
* Being vault

* Add markdown linting to pre-commit hook

* Add rest of initial notes

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -22,6 +22,13 @@ function exit_gracefully {
 
 makeStash
 
+# Check markdown
+npx markdownlint-cli2 "**/*.md"
+if [[ $? -ne 0 ]]; then
+  echo -e "\e[31mMarkdown linting failed. Fix the errors above and try again.\e[0m"
+  exit_gracefully 1
+fi
+
 # Check formatting
 for nonHaskellFile in $(git ls-files | sed '/\.hs$/d'); do
   git checkout HEAD -- $nonHaskellFile
